name: snne
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - cuda-toolkit
  - pip
  - pytorch==2.4.0
  - torchvision==0.19.0
  - torchaudio==2.4.0
  - pytorch-cuda=12.4
  - numpy
  - transformers
  - evaluate
  - datasets
  - pip:
    - transformers
    - scikit-learn
    - pandas
    - flake8
    - omegaconf
    - jupyterlab
    - notebook
    - matplotlib
    - seaborn
    - tqdm
    - ipywidgets
    - scipy
    - wandb
    - tokenizers>=0.13.3
    - accelerate==0.30.0
    - ml_collections
    - torchmetrics==1.4.1
    - openai
    - tiktoken
    - einops
    - bitsandbytes
    - nltk
    - tenacity
    - sentencepiece
    - safetensors
    - ninja
    - sentence-transformers
    - peft==0.12.0
    - rouge_score
    - bert-score
    - vllm
    - latex2sympy2
    - loguru
    - networkx
